/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.75
 * Generated at: 2023-07-24 06:04:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.product;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class productForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1689560285225L));
    _jspx_dependants.put("jar:file:/C:/ak/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/market/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>상품 등록</title>\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/bootstrap.css\">\n");
      out.write("<script src=\"resources/js/bootstrap.js\"></script>\n");
      out.write("<script src=\"resources/js/validation.js\"></script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../header.jsp", out, false);
      out.write("\n");
      out.write("	<div class=\"container my-4\">\n");
      out.write("		<h2 class=\"text-left mx-4 my-4\">상품 등록</h2>\n");
      out.write("		<div class=\"row mx-5\">\n");
      out.write("			<form action=\"/addProduct.do\" method=\"post\"\n");
      out.write("			  encType=\"multipart/form-data\" name=\"newProduct\">\n");
      out.write("				<div class=\"form-group row\">\n");
      out.write("					<label class=\"col-sm-2\">상품 코드</label>\n");
      out.write("					<div class=\"col-sm-3 my-2\">\n");
      out.write("						<input type=\"text\" name=\"productId\" id=\"productId\" class=\"form-control\">\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"form-group row\">\n");
      out.write("					<label class=\"col-sm-2\">상품명</label>\n");
      out.write("					<div class=\"col-sm-3 my-2\">\n");
      out.write("						<input type=\"text\" name=\"pname\" id=\"pname\" class=\"form-control\">\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"form-group row\">\n");
      out.write("					<label class=\"col-sm-2\">가격</label>\n");
      out.write("					<div class=\"col-sm-3 my-2\">\n");
      out.write("						<input type=\"text\" name=\"unitPrice\" id=\"unitPrice\" class=\"form-control\">\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"form-group row\">\n");
      out.write("					<label class=\"col-sm-2\">상품 설명</label>\n");
      out.write("					<div class=\"col-sm-5 my-2\">\n");
      out.write("						<textarea rows=\"2\" cols=\"50\" name=\"description\"\n");
      out.write("						          class=\"form-control\"></textarea>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"form-group row\">\n");
      out.write("					<label class=\"col-sm-2\">제조사</label>\n");
      out.write("					<div class=\"col-sm-3 my-2\">\n");
      out.write("						<input type=\"text\" name=\"manufacturer\" class=\"form-control\">\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"form-group row\">\n");
      out.write("					<label class=\"col-sm-2\">분류</label>\n");
      out.write("					<div class=\"col-sm-3 my-2\">\n");
      out.write("						<input type=\"text\" name=\"category\" class=\"form-control\">\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"form-group row\">\n");
      out.write("					<label class=\"col-sm-2\">재고수</label>\n");
      out.write("					<div class=\"col-sm-3 my-2\">\n");
      out.write("						<input type=\"text\" name=\"unitsInStock\" id=\"unitsInStock\" class=\"form-control\">\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"form-group row\">\n");
      out.write("					<label class=\"col-sm-2\"></label>\n");
      out.write("					<div class=\"col-sm-5 my-2\">\n");
      out.write("						<label><input type=\"radio\" name=\"condition\" value=\"New\">신상품</label>\n");
      out.write("						<label><input type=\"radio\" name=\"condition\" value=\"Old\">중고품</label>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"form-group row\">\n");
      out.write("					<label class=\"col-sm-2\">상품 이미지</label>\n");
      out.write("					<div class=\"col-sm-5 my-2\">\n");
      out.write("						<input type=\"file\" name=\"productImage\" class=\"form-control\">\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"form-group row\">\n");
      out.write("					<div class=\"col-sm-3 my-2\">\n");
      out.write("						<input type=\"button\" value=\"등록\" \n");
      out.write("							class=\"btn btn-primary\" onclick=\"checkAddProduct()\">\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</form>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../footer.jsp", out, false);
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
